# ─────────────────────────────────────────────
# VPC Network
# ─────────────────────────────────────────────

resource "google_compute_network" "educates" {
  name                    = var.network_name
  auto_create_subnetworks = false
  project                 = var.project_id
}

resource "google_compute_subnetwork" "educates" {
  name          = var.subnet_name
  network       = google_compute_network.educates.id
  region        = var.region
  project       = var.project_id
  ip_cidr_range = var.subnet_cidr

  # Secondary ranges required for GKE alias IPs (VPC-native networking)
  secondary_ip_range {
    range_name    = "pods"
    ip_cidr_range = var.pods_cidr
  }

  secondary_ip_range {
    range_name    = "services"
    ip_cidr_range = var.services_cidr
  }

  private_ip_google_access = true
}

# ─────────────────────────────────────────────
# Static external IP for the Contour ingress LB
# ─────────────────────────────────────────────

resource "google_compute_address" "ingress" {
  name    = "${var.cluster_name}-ingress-ip"
  region  = var.region
  project = var.project_id

  labels = var.labels
}

# ─────────────────────────────────────────────
# GKE Standard Cluster
#
# Educates requirements (from docs.educates.dev):
#   - Standard cluster (NOT Autopilot) — Kyverno needs privileged containers
#   - NetworkPolicy enabled           — required by Kyverno
#   - Workload Identity               — required for GKE provider
#   - Container-Optimized OS + containerd (COS_CONTAINERD)
#   - ≥ 4 vCPU / 16 GB RAM per node (n2-standard-4 default)
#   - ≥ 3 worker nodes
# ─────────────────────────────────────────────

resource "google_container_cluster" "educates" {
  name     = var.cluster_name
  location = var.zone
  project  = var.project_id

  # Remove the default node pool immediately; we manage our own below.
  remove_default_node_pool = true
  initial_node_count       = 1

  network    = google_compute_network.educates.id
  subnetwork = google_compute_subnetwork.educates.id

  # VPC-native (alias IP) networking — required for secondary ranges
  networking_mode = "VPC_NATIVE"
  ip_allocation_policy {
    cluster_secondary_range_name  = "pods"
    services_secondary_range_name = "services"
  }

  # Network Policy — required by Educates / Kyverno
  network_policy {
    enabled  = true
    provider = "CALICO"
  }

  # Workload Identity — required for GKE
  dynamic "workload_identity_config" {
    for_each = var.enable_workload_identity ? [1] : []
    content {
      workload_pool = "${var.project_id}.svc.id.goog"
    }
  }

  # Minimum master version (empty string defers to the release channel default)
  min_master_version = var.kubernetes_version != "" ? var.kubernetes_version : null

  # Release channel — REGULAR keeps patch versions stable between applies
  release_channel {
    channel = var.kubernetes_version != "" ? "UNSPECIFIED" : "REGULAR"
  }

  # Allow deletion without protection (suitable for ephemeral workshop environments)
  deletion_protection = false

  resource_labels = var.labels
}

# ─────────────────────────────────────────────
# Dedicated Node Pool
# ─────────────────────────────────────────────

resource "google_container_node_pool" "educates_nodes" {
  name     = "${var.cluster_name}-nodes"
  cluster  = google_container_cluster.educates.id
  location = var.zone
  project  = var.project_id

  node_count = var.node_count

  node_config {
    machine_type = var.machine_type
    disk_size_gb = var.node_disk_size_gb
    disk_type    = var.node_disk_type

    # Container-Optimized OS with containerd — required by Educates on GKE
    image_type = "COS_CONTAINERD"

    # Workload Identity on nodes
    dynamic "workload_metadata_config" {
      for_each = var.enable_workload_identity ? [1] : []
      content {
        mode = "GKE_METADATA"
      }
    }

    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform",
    ]

    labels = var.labels

    shielded_instance_config {
      enable_secure_boot          = true
      enable_integrity_monitoring = true
    }
  }

  management {
    auto_repair  = true
    auto_upgrade = true
  }

  upgrade_settings {
    max_surge       = 1
    max_unavailable = 0
  }
}

# ─────────────────────────────────────────────
# Educates platform config file
#
# Written to the working directory after apply.
# Pass it to: educates deploy-platform --config educates-config.yaml
# ─────────────────────────────────────────────

resource "local_file" "educates_config" {
  filename        = "${path.module}/educates-config.yaml"
  file_permission = "0644"

  content = <<-YAML
    # Educates platform configuration for GKE
    # Generated by Terraform — do not edit manually.
    #
    # Usage:
    #   gcloud container clusters get-credentials ${google_container_cluster.educates.name} \
    #     --zone ${var.zone} --project ${var.project_id}
    #   educates deploy-platform --config educates-config.yaml

    clusterInfrastructure:
      provider: gke

    clusterIngress:
      domain: "${var.ingress_domain}"
      # Point *.${var.ingress_domain} at the static IP below before running deploy-platform.
      # Static IP: ${google_compute_address.ingress.address}

    clusterPackages:
      contour:
        enabled: true
        settings:
          infrastructure:
            loadBalancerIP: "${google_compute_address.ingress.address}"
      certManager:
        enabled: true
      kyverno:
        enabled: true
      educates:
        enabled: true
  YAML
}
